#!/bin/bash
PSQL="psql --username=freecodecamp --dbname=periodic_table -t --no-align -c"
if [[ $1 ]]
then
  ISNUMBER='false'
  if [[ $1 =~ [0-9] ]]
  then
    ISNUMBER='true'
  fi
  if [[ $ISNUMBER == 'true' ]]
  then
    ISELEMENT=$($PSQL "SELECT * FROM elements FULL JOIN properties USING(atomic_number) FULL JOIN types USING(type_id) WHERE elements.atomic_number = $1")
  else
    ISELEMENT=$($PSQL "SELECT * FROM elements FULL JOIN properties USING(atomic_number) FULL JOIN types USING(type_id) WHERE name = '$1' OR symbol = '$1'")
  fi
  if [[ -z $ISELEMENT ]]
  then
    echo -e "I could not find that element in the database."
  else
    IFS='|' read TYPEID ATOMNUM SYMBOL NAME ATOMMASS MELTINGPOINT BOILINGPOINT TYPE <<< $ISELEMENT
    echo -e "The element with atomic number $ATOMNUM is $NAME ($SYMBOL). It's a $TYPE, with a mass of $ATOMMASS amu. $NAME has a melting point of $MELTINGPOINT celsius and a boiling point of $BOILINGPOINT celsius."
  fi
else
  echo -e "Please provide an element as an argument."
  exit
fi
