#!/bin/bash
PSQL="psql -X --username=freecodecamp --dbname=salon --tuples-only -c"
echo -e "\n~~~~~ SP SALON ~~~~~"
MAIN_MENU() {
  if [[ ! $1 ]]
  then
    echo -e "\nWelcome to SP Salon, which service are you looking to have done?\n"
  else
    echo -e "\n$1\n"
  fi
  echo "$($PSQL "SELECT * FROM services")" | while IFS=" | " read SERID SERNAME
  do
  echo "$SERID) $SERNAME"
  done
  read SERVICE_ID_SELECTED
  if [[ $SERVICE_ID_SELECTED =~ [^0-9] ]]
  then
    MAIN_MENU "A non-number character was detected. Please enter a valid number for the service."
  else
    ISSERVICE=$($PSQL "SELECT service_id FROM services WHERE service_id=$SERVICE_ID_SELECTED")
    if [[ -z $ISSERVICE ]]
    then
      MAIN_MENU "The requested service does not exist. Please enter a valid number for the service."
    else
      SERVICENAME=$($PSQL "SELECT name FROM services WHERE service_id=$SERVICE_ID_SELECTED")
      echo -e "\nPlease enter your phone number in the 111-111-1111 format."
      read CUSTOMER_PHONE
      ISPHONENUMBER=$($PSQL "SELECT * FROM customers WHERE phone = '$CUSTOMER_PHONE'") 
      if [[ -z $ISPHONENUMBER ]]
      then
        echo -e "\nIt seems that we don't have your phone on record. Please enter your name."
        read CUSTOMER_NAME
        INSERTRESULT=$($PSQL "INSERT INTO customers(phone, name) VALUES('$CUSTOMER_PHONE', '$CUSTOMER_NAME')")
        echo -e "\nWe have successfully registered name $CUSTOMER_NAME with the phone number $CUSTOMER_PHONE."
      else
        CUSTOMER_NAME=$($PSQL "SELECT name FROM customers WHERE phone = '$CUSTOMER_PHONE'")
      fi
      CUSTOMER_ID=$($PSQL "SELECT customer_id FROM customers WHERE phone = '$CUSTOMER_PHONE'")
      echo -e "\nAt what time would you like to make a $SERVICENAME appointment $CUSTOMER_NAME?\nPlease enter a time with the HH:MM format. Ex: '09:30'."
      read SERVICE_TIME
      INSERTRESULT2=$($PSQL "INSERT INTO appointments(customer_id, service_id, time) VALUES($CUSTOMER_ID, $SERVICE_ID_SELECTED, '$SERVICE_TIME')")
      echo -e "\nI have put you down for a $SERVICENAME at $SERVICE_TIME, $CUSTOMER_NAME."
    fi
  fi
}

MAIN_MENU
