#!/bin/bash
#Definitions
RANDNUM=$((($RANDOM % 1000) + 1))
PSQL="psql --username=freecodecamp --dbname=number_guess -t --no-align -c"
#Startup sequence
echo -e "\nEnter your username:"
read USERNAME
ISUSERNAME=$($PSQL "SELECT * FROM users WHERE username = '$USERNAME'")
if [[ -z $ISUSERNAME ]]
then
  echo -e "\nWelcome, $USERNAME! It looks like this is your first time here."
  INSERTRESULT=$($PSQL "INSERT INTO users(username, games_played, best_game) VALUES('$USERNAME', 0, NULL)")
  GAMESPLAYED=0
  USERID=$($PSQL "SELECT user_id FROM users WHERE username = '$USERNAME'")
else
  IFS="|" read USERID USERNAME_DUP GAMESPLAYED BESTGAME <<< $ISUSERNAME
  echo -e "\nWelcome back, $USERNAME! You have played $GAMESPLAYED games, and your best game took $BESTGAME guesses."
fi
#Game loop
GAMESPLAYED=$((GAMESPLAYED+1))
CURRENTCOUNT=1
GAMELOOP() {
  #Compares previous answer to generated number to output text
  if [[ $1 ]]
  then
    if [[ $1 =~ ^[0-9]+$ ]]
    then
      CURRENTCOUNT=$((CURRENTCOUNT+1))
      if [[ $1 -lt $RANDNUM ]]
      then
        echo -e "\nIt's higher than that, guess again:"
      elif [[ $1 -gt $RANDNUM ]]
      then
        echo -e "\nIt's lower than that, guess again:"
      fi
    else
      echo -e "\nThat is not an integer, guess again:"
    fi
  else
    echo -e "\nGuess the secret number between 1 and 1000:"
  fi

  read NUMBGUESS
  if [[ $NUMBGUESS =~ ^[0-9]+$ ]]
  then
    if ((NUMBGUESS==RANDNUM))
    then
      echo -e "You guessed it in $CURRENTCOUNT tries. The secret number was $RANDNUM. Nice job!"
      if [[ $CURRENTCOUNT -lt $BESTGAME || $BESTGAME == "" ]]
      then
        INSERTRESULT=$($PSQL "UPDATE users SET games_played = $GAMESPLAYED, best_game = $CURRENTCOUNT WHERE user_id = $USERID")
      else
        INSERTRESULT=$($PSQL "UPDATE users SET games_played = $GAMESPLAYED WHERE user_id = $USERID")
      fi
      exit
    else
      GAMELOOP $NUMBGUESS
      return
    fi
  else
    GAMELOOP $NUMBGUESS
    return
  fi
}
GAMELOOP
