#! /bin/bash

if [[ $1 == "test" ]]
then
  PSQL="psql --username=postgres --dbname=worldcuptest -t --no-align -c"
else
  PSQL="psql --username=freecodecamp --dbname=worldcup -t --no-align -c"
fi

# Do not change code above this line. Use the PSQL variable above to query your database.
$PSQL " TRUNCATE TABLE teams, games"
cat games.csv | while IFS="," read YEAR ROUND WINNER OPPONENT WINNERGOALS OPPONENTGOALS
do
  if [[ $YEAR != 'year' ]] 
  then
    #Checks if winner exists in the team table, inserts if not and returns team_id
    ISWINNER=$($PSQL "SELECT team_id FROM teams WHERE name = '$WINNER'")
    if [[ -z $ISWINNER ]] 
    then
      $PSQL "INSERT INTO teams(name) VALUES('$WINNER')"
      ISWINNER=$($PSQL "SELECT team_id FROM teams WHERE name = '$WINNER'")
    fi
    
    #Checks if opponent exists in the team table, inserts if not and returns team_id
    ISOPPONENT=$($PSQL "SELECT team_id FROM teams WHERE name = '$OPPONENT'")
    if [[ -z $ISOPPONENT ]] 
    then
      $PSQL "INSERT INTO teams(name) VALUES('$OPPONENT')"
      ISOPPONENT=$($PSQL "SELECT team_id FROM teams WHERE name = '$OPPONENT'")
    fi

    $PSQL "INSERT INTO games(year, round, winner_id, opponent_id, winner_goals, opponent_goals) VALUES($YEAR, '$ROUND', $ISWINNER, $ISOPPONENT, $WINNERGOALS, $OPPONENTGOALS)"
    
  fi
done
